apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: Orchsky-cluster
  region: us-east-1

nodeGroups:
  - name: Orchsky-nodegroup
    instanceType: t2.small
    desiredCapacity: 2
    ssh:
      publicKeyName: <key pair name>