apiVersion: v1
kind: Service
metadata:
  name: registerapp-service 
  labels:
    app: orchsky-app
spec: 
  selector:
    app: orchsky-app

  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer